Profile/urls.py
from django.urls import path
from . import views
app_name = 'Profile'
urlpatterns = [
    path('profile',views.profile_main_page,name='profile'),
    path('profile/orders', views.profile_user_order, name="orders"),
    path('profile/setting', views.profile_setting, name="setting"),

]

Shop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from Shop import settings
from .views import home , header ,footer,login_page,register_page,log_out
from products.views import ProductsList, products_categories_partial
from contact.views import contact_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home,name='home'),
    path('header',header,name='header'),
    path('footer',footer,name='footer'),
    path('login',login_page,name='login'),
    path('register',register_page,name='register'),
    path('logout',log_out,name='logout'),
    path('',include('products.urls',namespace='products')),
    path('',include('order.urls',namespace='order')),
    path('',include('Profile.urls',namespace='Profile')),
    path('products_categories_partial',products_categories_partial,name='products_categories_partial'),
    path('contact',contact_page,name='contact')
   
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views
app_name = 'order'
urlpatterns = [
    path('add_new_order',views.add_new_order,),
    path('cart',views.cart,name='cart'),
    path('remove_cart/<detail_id>',views.remove_cart,name='remove_cart')
]

Profile/models.py
from django.db import models

# Create your models here.

Profile/forms.py
from django import forms


class UserEditProfileForm(forms.Form):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'نام خود را وارد نمایید'}),
    )

    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'نام خانوادگی خود را وارد نمایید.'}),
    )

Profile/views.py
from django.http import Http404
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from order.models import Order
from .forms import UserEditProfileForm
from django.contrib.auth.models import User

# Create your views here.
@login_required(login_url='/login')
def profile_main_page(request):
    context ={}
    return render(request,'profile.html',context)

@login_required(login_url='/login')
def profile_user_order(request):
    open_order = None
    order_items = []
    total_price = 0
    
    if request.user.is_authenticated:
        open_order = Order.objects.filter(user_id=request.user.id, paid=False).first()
        if open_order:
            order_items = open_order.order_detail_set.all()  
            total_price = open_order.total_price() if hasattr(open_order, 'total_price') else 0
    
    context = {
        'order': order_items,  
        'total_price': total_price
    }
    return render(request,'profile_order.html',context)

@login_required(login_url='/login')
def profile_sidebar(request):
    context ={}
    return render(request,'profile_sidebar.html',context)

@login_required(login_url='/login')
def profile_setting(request):
    user_id = request.user.id
    user = User.objects.get(id=user_id)
    if user is None:
        raise Http404()

    edit_form = UserEditProfileForm(request.POST or None, initial={'first_name':user.first_name, 'last_name':user.last_name})
    if edit_form.is_valid():
        first_name = edit_form.cleaned_data.get('first_name')
        last_name = edit_form.cleaned_data.get('last_name')
        user.first_name = first_name
        user.last_name = last_name
        user.save()

    context = {
        'edit_form': edit_form
    }
    return render(request, 'profile_setting.html', context)

Profile/templates/profile.html
{% extends 'base/base.html' %}
{% load render_partial %}

{% block content %}
    <div class="container">
      <div class="row">
       <!--Right Part Start -->
        <aside id="column-right" class="col-sm-3 hidden-xs">
            {% render_partial 'Profile.views.profile_sidebar' %}
        </aside>

        <!--Right Part End -->
        <!--Middle Part Start-->
        <div id="content" class="col-sm-9">
          <h1 class="title">پنل کاربر</h1>
        </div>
        <!--Middle Part End -->
      </div>
    </div>
{% endblock %}

Profile/templates/profile_order.html
{% extends 'base/base.html' %}
{% load render_partial %}

{% block content %}
<div class="container">
  <div class="row">
    <!--Right Part Start -->
    <aside id="column-right" class="col-sm-3 hidden-xs">
      {% render_partial 'Profile.views.profile_sidebar' %}
    </aside>
    <!--Right Part End -->
    <!--Middle Part Start-->
    <div id="content" class="col-sm-9">
      <h1 class="title">سفارش های من</h1>
      <ul class="">
        <li>
          <table class="table">
            <tbody>
              {% for orders in order %}
              <tr>
                <td class="text-center"><a href="{% url 'order:cart' %}"><img class="img-thumbnail"
                      title="{{orders.title}}" alt="{{orders.title}}" src="{{orders.product.image.url}}"></a></td>
                <td class="text-left"><a href="{{orders.product.get_product_detail_url}}">{{orders.product.title}}</a>
                </td>
                <td class="text-right">{{orders.count}}</td>
                <td class="text-right">{{orders.price}} تومان</td>
                <td class="text-center"><a href="/remove_cart/{{orders.id}}"><button
                      class="btn btn-danger btn-xs remove" title="حذف" type="button"><i
                        class="fa fa-times"></i></button></a></td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </li>
        <li>
          <div>
            <table class="table table-bordered">
              <tbody>
                <tr>
                  <td class="text-right"><strong>جمع کل</strong></td>
                  <td class="text-right">{{total_price}} تومان</td>
                </tr>
                <tr>
                  <td class="text-right"><strong>قابل پرداخت</strong></td>
                  <td class="text-right">{{total_price}} تومان</td>
                </tr>
              </tbody>
            </table>
            <p class="checkout"><a href="/cart" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> مشاهده
                سبد</a>&nbsp;&nbsp;&nbsp;<a href="checkout.html" class="btn btn-primary"><i class="fa fa-share"></i>
                تسویه
                حساب</a>
            </p>
          </div>
        </li>
      </ul>
    </div>
    <!--Middle Part End -->
  </div>
</div>
{% endblock %}

Profile/templates/profile_setting.html
{% extends 'base/base.html' %}
{% load render_partial %}

{% block content %}
<div class="container">
  <div class="row">
    <!--Right Part Start -->
    <aside id="column-right" class="col-sm-3 hidden-xs">
      {% render_partial 'Profile.views.profile_sidebar' %}
    </aside>
    <!--Right Part End -->
    <!--Middle Part Start-->
    <div id="content" class="col-sm-9">
      <h1 class="title">تنظیمات</h1>

      <form class="form-horizontal" method="post">
        {% csrf_token %}
        <fieldset>
          <div class="form-group required">
            <label class="col-md-2 col-sm-3 control-label" for="input-name">{{ edit_form.first_name.label }}</label>
            <div class="col-md-10 col-sm-9">
              {{edit_form.first_name }}
            </div>
            {% for error in edit_form.first_name.errors %}
            <div class="text-danger">{{ error }}</div>
            {% endfor %}
          </div>

          <div class="form-group required">
            <label class="col-md-2 col-sm-3 control-label" for="input-name">{{ edit_form.last_name.label }}</label>
            <div class="col-md-10 col-sm-9">
              {{edit_form.last_name }}
            </div>
            {% for error in edit_form.last_name.errors %}
            <div class="text-danger">{{ error }}</div>
            {% endfor %}
          </div>

        </fieldset>
        <div class="buttons">
          <div class="pull-right">
            <input class="btn btn-primary" type="submit" value="ارسال">
          </div>
        </div>
      </form>

    </div>
    <!--Middle Part End -->
  </div>
</div>
{% endblock %}

Profile/templates/profile_sidebar.html
<ul>
    <li>
        <a href="/profile">پنل کاربر</a>
    </li>
    <li>
        <a href="{% url 'Profile:orders' %}">سفارش های من</a>
    </li>
    <li>
        <a href="{% url 'Profile:setting' %}">تنظیمات</a>
    </li>
    <li>
        <a href="/logout">خروج</a>
    </li>
</ul>