Shop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from Shop import settings
from .views import home , header ,footer,login_page,register_page,log_out
from products.views import ProductsList, products_categories_partial
from contact.views import contact_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home,name='home'),
    path('header',header,name='header'),
    path('footer',footer,name='footer'),
    path('login',login_page,name='login'),
    path('register',register_page,name='register'),
    path('logout',log_out,name='logout'),
    path('',include('products.urls',namespace='products')),
    path('',include('order.urls',namespace='order')),
    path('',include('Profile.urls',namespace='Profile')),
    path('products_categories_partial',products_categories_partial,name='products_categories_partial'),
    path('contact',contact_page,name='contact')
   
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views
app_name = 'order'
urlpatterns = [
    path('add_new_order',views.add_new_order,),
    path('cart',views.cart,name='cart'),
    path('remove_cart/<detail_id>',views.remove_cart,name='remove_cart')
]

order/models.py
from django.db import models
from django.contrib.auth.models import User

from products.models import Products
# Create your models here.
class Order(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    paid = models.BooleanField(default=False)
    pay_date = models.DateTimeField(blank=True,null=True)


    def __str__(self):
        return self.user.get_full_name()
    
    def total_price(self):
        amount = 0
        for detail in self.order_detail_set.all():
            amount += detail.price * detail.count
        return amount

    
class Order_Detail(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    product = models.ForeignKey(Products,on_delete=models.CASCADE)
    count = models.IntegerField()
    price = models.IntegerField()


    def __str__(self):
        return self.product.title
    
    def product_sum_in_cart(self):
        return self.price * self.count

order/forms.py
from django import forms


class UserNewOrderForm(forms.Form):
    product_id = forms.IntegerField(
        widget=forms.HiddenInput(
            attrs={})
    )

    count = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={'class': 'form-control', 'id': 'input-quantity'}),
            initial= 1 
    )

order/views.py
from django.contrib import messages
from django.http import Http404
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from order.models import Order, Order_Detail
from products.models import Products
from .forms import UserNewOrderForm
# Create your views here.


@login_required(login_url='/login')
def add_new_order(request):
    new_order_form = UserNewOrderForm(request.POST or None)
    
    if new_order_form.is_valid():
        order = Order.objects.filter(user_id=request.user.id, paid=False).first()
        if order is None:
            order = Order.order_detail_set.create(user_id=request.user.id, paid=False)

        product_id = new_order_form.cleaned_data.get('product_id')
        count = new_order_form.cleaned_data.get('count')
        

        product = Products.objects.get_product_by_id(product_id)
        if product is None:
            messages.error(request, "محصول مورد نظر یافت نشد!")
            return redirect('home')  

        if count < 0:
            count = 1


        existing_order_detail = Order_Detail.objects.filter(
            order=order,
            product_id=product.id
        ).first()

        if existing_order_detail:
            existing_order_detail.count += count
            existing_order_detail.save()
            messages.success(request, f"تعداد {product.title} به {existing_order_detail.count} افزایش یافت")
        else:
        
            order.order_detail_set.create( 
                product_id=product.id, 
                count=count, 
                price=product.price
            )
            messages.success(request, f"{product.title} به سبد خرید اضافه شد")

        return redirect(f'/products/{product.id}/{product.title.replace(" ", "-")}')
    
    else:

        messages.error(request, "خطا در افزودن به سبد خرید")
        return redirect('home')  
@login_required(login_url='/login')
def cart(request):
    context = {
        'order': None,
        'details': None,
        'total_price': 0 
    }
    open_order: Order = Order.objects.filter(user_id=request.user.id, paid=False).first()
    
    if open_order is not None:  
        context['order'] = open_order
        context['details'] = open_order.order_detail_set.all()
        context['total_price'] = open_order.total_price()

    return render(request, 'cart.html', context)


@login_required(login_url='/login')
def remove_cart(request, *args, **kwargs):
    detail_id = kwargs['detail_id']
    action = request.GET.get('action', 'remove_one')  
    
    try:
        order_detail = Order_Detail.objects.get(
            id=detail_id, 
            order__user_id=request.user.id,
            order__paid=False
        )
        
        if action == 'remove_one':
            if order_detail.count > 1:
                order_detail.count -= 1
                order_detail.save()
            else:
                order_detail.delete()
                
        elif action == 'remove_all':
            order_detail.delete()
            
        return redirect('/cart')
        
    except Order_Detail.DoesNotExist:
        raise Http404()

order/templates/cart.html
{% extends "base/base.html" %}
{% block content %}
<div id="content" class="col-sm-12">
          <h1 class="title">سبد خرید</h1>
            <div class="table-responsive">
              {% if order != None and details|length > 0 %}
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <td class="text-center">تصویر</td>
                    <td class="text-left">نام محصول</td>
                    <td class="text-left">کد محصول</td>
                    <td class="text-left">تعداد</td>
                    <td class="text-right">قیمت واحد</td>
                    <td class="text-right">کل</td>
                    <td class="text-right">عملیات</td>
                  </tr>
                </thead>
                <tbody>
                  {% for detail in details %}
                  <tr>
                    <td class="text-center"><a href="{{detail.product.get_product_detail_url}}"><img src="{{detail.product.image.url}}" alt="{{detail.product.title}}" title="{{detail.product.title}}" class="img-thumbnail"></a></td>
                    <td class="text-left"><a href="{{detail.product.get_product_detail_url}}">{{detail.product.title}}</a><br></td>
                    <td class="text-left">{{detail.product.id}}</td>
                    <td class="text-left"><div class="input-group btn-block quantity">
                        <span>{{detail.count}}</span>
                        <span class="input-group-btn">
                        </span></div></td>
                    <td class="text-right">{{detail.product.price}} تومان</td>
                    <td class="text-right">{{detail.product_sum_in_cart}} تومان<</td>
                    <td class="text-right">
                        <!-- حذف یک عدد -->
                        <a href="{% url 'order:remove_cart' detail.id %}?action=remove_one" 
                           class="btn btn-warning btn-sm" title="حذف یک عدد">
                            ➖ یک عدد
                        </a>
                        <!-- حذف کامل -->
                        <a href="{% url 'order:remove_cart' detail.id %}?action=remove_all" 
                           class="btn btn-danger btn-sm" title="حذف همه">
                            ❌ همه
                        </a>
                    </td>
                  </tr>
                  {% endfor %}

                </tbody>
              </table>
              {% else %}
              <p>هیچ محصول مورد نطری یافت نشد</p>
              {% endif %}
            </div>
          <div class="row">
            <div class="col-sm-4 col-sm-offset-8">
              <table class="table table-bordered">
                <tbody><tr>
                  <td class="text-right"><strong>جمع کل:</strong></td>
                  <td class="text-right">{{total_price}} تومان</td>
                </tr>
                <tr>
                  <td class="text-right"><strong>مالیات:</strong></td>
                  <td class="text-right">0 تومان</td>
                </tr>
                <tr>
                  <td class="text-right"><strong>قابل پرداخت :</strong></td>
                  <td class="text-right">{{total_price}} تومان</td>
                </tr>
              </tbody></table>
            </div>
          </div>
          <div class="buttons">
            <div class="pull-left"><a href="{% url 'home' %}" class="btn btn-default">ادامه خرید</a></div>
            <div class="pull-right"><a href="checkout.html" class="btn btn-primary">تسویه حساب</a></div>
          </div>
        </div>
{% endblock content %}