Shop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from Shop import settings
from .views import home , header ,footer,login_page,register_page,log_out
from products.views import ProductsList, products_categories_partial
from contact.views import contact_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home,name='home'),
    path('header',header,name='header'),
    path('footer',footer,name='footer'),
    path('login',login_page,name='login'),
    path('register',register_page,name='register'),
    path('logout',log_out,name='logout'),
    path('',include('products.urls',namespace='products')),
    path('',include('order.urls',namespace='order')),
    path('',include('Profile.urls',namespace='Profile')),
    path('products_categories_partial',products_categories_partial,name='products_categories_partial'),
    path('contact',contact_page,name='contact')
   
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import include, path
from .views import ProductsList ,SearchProducts,ProductsListByCategory
from . import views

app_name = 'products'

urlpatterns = [
    path('products',ProductsList.as_view(),name='products_list'),
    path('products/<product_id>/<title>',views.product_detail,name='product_detail'),
    path('products/search', SearchProducts.as_view()),
    path('products/<category_name>', ProductsListByCategory.as_view()),
    
   
]

category/models.py
from django.db import models

# Create your models here.
class ProductCategory(models.Model):
    title = models.CharField(max_length=100)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.title

products/models.py
from django.db import models
import random
import os
from django.db.models import Q

from category.models import ProductCategory

def get_file_extension(file):
    base_name = os.path.basename(file)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image(instance, filename):
    rand_name = random.randint(1, 99999999999999)
    name, ext = get_file_extension(filename)
    final_name = f"{instance.id}-{instance.title}-{rand_name}{ext}"
    return f"products/{final_name}"

def upload_image_gallery(instance, filename):
    rand_name = random.randint(1, 99999999999999)
    name, ext = get_file_extension(filename)
    final_name = f"{instance.id}-{instance.title}-{rand_name}{ext}"
    return f"gallery/{final_name}"


class ProductManager(models.Manager):
    def get_active_products(self):
        return self.get_queryset().filter(active =True)
    
    def get_product_by_id(self,product_id):
        qs =self.get_queryset().filter(id = product_id,active=True) 
        if qs.count() == 1:
            return qs.first()
        else:
            return None
        
    def search_products(self, query):
        lookup = (
                Q(title__icontains=query) |
                Q(description__icontains=query) |
                Q(tag__title__icontains=query)

        )
        return self.get_queryset().filter(lookup, active=True).distinct()
    
    def get_product_by_category(self,category_name):
        return self.get_queryset().filter(categories__name__iexact = category_name)


# Create your models here.
class Products(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=15,decimal_places=2)
    image = models.ImageField(upload_to=upload_image,null=True,blank=True)
    active = models.BooleanField(default=False)
    time = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField(ProductCategory,blank=True)
    featured = models.BooleanField(default=False)
    visits = models.IntegerField(default=0,editable=False)

    objects = ProductManager()
    def __str__(self):
        return self.title
    
    def get_product_detail_url(self):
        return f'/products/{self.id}/{self.title.replace(' ','-')}'
    


class ProductGallery(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to=upload_image_gallery,null=True,blank=True)
    product = models.ForeignKey(Products,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

category/views.py
from django.shortcuts import render

# Create your views here.

products/views.py
from django.http import Http404
from django.shortcuts import render

from category.models import ProductCategory
from .models import Products
from django.views.generic.list import ListView
from .models import Products, ProductGallery
from order.forms import UserNewOrderForm
# Create your views here.


class ProductsList(ListView):
    template_name = 'products_list.html'
    paginate_by = 1

    def get_queryset(self):
        return Products.objects.get_active_products()


class ProductsListByCategory(ListView):
    template_name = 'products_list.html'
    paginate_by = 4

    def get_queryset(self):
        category_name = self.kwargs['category_name']
        categories = ProductCategory.objects.filter(name__iexact=category_name)
        if categories is None:
            raise Http404('page not found ):')
        return Products.objects.get_product_by_category(category_name)


def products_categories_partial(request):
    categories = ProductCategory.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'category.html', context)


def product_detail(request, *args, **kwargs):
    product_id = kwargs['product_id']
    title = kwargs['title']
    new_user_form = UserNewOrderForm(request.POST or None,initial=({'product_id':product_id}))

    product = Products.objects.get_product_by_id(product_id)
    if product is None:
        raise Http404('محصول مورد نظر یافت نشد')
    
    product.visits =+ 1
    product.save()

    gallery = ProductGallery.objects.filter(product_id=product_id)

    related_product= Products.objects.filter(categories__in=product.categories.all()).exclude(id=product.id)

    context = {
        'product': product,
        'gallery': gallery,
        'related_product':related_product ,
        'new_user_form':new_user_form
    }
    return render(request, 'product_detail.html', context)


class SearchProducts(ListView):
    template_name = 'products_list.html'
    paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get('q')
        print(query)
        if query is not None:
            return Products.objects.search_products(query)

        return Products.objects.get_active_products()

products/templates/category.html
<!-- <aside id="column-left" class="col-sm-3 hidden-xs"> -->
    <a href="{% url 'products:products_list' %}"><h3 class="subtitle">دسته ها</h3></a>
    <div class="box-category">
        <ul>
            {% for category in categories %}
            <li><a href="/products/{{category.name}}">{{ category.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
<!-- </aside> -->

products/templates/product_detail.html
{% extends 'base/base.html' %}
{% load static %}
{% load render_partial %}

{% block content %}

    <div class="container">
      <!-- Breadcrumb Start-->
      <ul class="breadcrumb">
        <li itemscope=""><a href="{% url 'home' %}" itemprop="url"><span itemprop="title"><i class="fa fa-home"></i></span></a></li>
        <li itemscope=""><a href="{% url 'products:products_list' %}" itemprop="url"><span itemprop="title">فروشگاه</span></a></li>
        <li itemscope=""><a href="#" itemprop="url"><span itemprop="title">لپ تاپ ایلین ور</span></a></li>
      </ul>


        <!-- Breadcrumb End-->
      <div class="row">
        <!--Middle Part Start-->
        <div id="content" class="col-sm-9">
          <div itemscope="" itemtype="http://schema.org/محصولات">
            <h1 class="title" itemprop="name">{{ product.title }}</h1>
            <div class="row product-info">
              <div class="col-sm-6">
                <div class="image"><div style="height:350px;width:100%" class="zoomWrapper">
                    <img class="img-responsive" itemprop="image" id="zoom_01" src="{{ product.image.url }}" alt="{{ product.title}}" style="position: absolute;">
                </div> </div>
                  <div class="image-additional" id="gallery_01">
                      {% for image_gallery in gallery %}
                            <a class="thumbnail" href="#" data-zoom-image="{{ image_gallery.image.url }}" data-image="{{ image_gallery.image.url }}"
                               title="{{ image_gallery.title }}">
                                <img src="{{ image_gallery.image.url }}" title="{{ image_gallery.title }}" alt="{{ image_gallery.title }}">
                            </a>
                      {% endfor %}
                  </div>
              </div>
              <div class="col-sm-6">
                <ul class="list-unstyled description">
                  <li><b>برند :</b> <a href="#"><span itemprop="brand">اپل</span></a></li>
                  <li><b>کد محصول :</b> <span itemprop="mpn">محصولات 17</span></li>
                  <li><b>امتیازات خرید:</b> 700</li>
                  <li><b>وضعیت موجودی :</b> <span class="instock">موجود</span></li>
                </ul>
                <ul class="price-box">
                  <li class="price" itemprop="offers" itemscope="" itemtype="http://schema.org/Offer">
                      <span class="price">{{ product.price }} تومان</span>
                  </li>
                  <li></li>
                  <li>بدون مالیات : 9 میلیون تومان</li>
                </ul>
                <div id="product">
                  <h3 class="subtitle">انتخاب های در دسترس</h3>
                  <div class="form-group required">
                    <label class="control-label">رنگ</label>
                    <select class="form-control" id="input-option200" name="option[200]">
                      <option value=""> --- لطفا انتخاب کنید --- </option>
                      <option value="4">مشکی </option>
                      <option value="3">نقره ای </option>
                      <option value="1">سبز </option>
                      <option value="2">آبی </option>
                    </select>
                  </div>
                  <div class="cart">
                      <div>
                      <form action="/add_new_order" method="post">
                          {% csrf_token %}
                          <div class="qty">
                              {{ new_user_form.product_id }}
                            <label class="control-label" for="input-quantity">تعداد</label>
                              {{new_user_form.count}}
                            <a class="qtyBtn plus" href="javascript:void(0);">+</a><br>
                            <a class="qtyBtn mines" href="javascript:void(0);">-</a>
                            <div class="clear"></div>
                          </div>
                          <button type="submit" id="button-cart" class="btn btn-primary btn-lg">افزودن به سبد خرید</button>
                      </form>
                    </div>
                    <div>
                      <button type="button" class="wishlist" onclick=""><i class="fa fa-heart"></i> افزودن به علاقه مندی ها</button>
                      <br>
                      <button type="button" class="wishlist" onclick=""><i class="fa fa-exchange"></i> مقایسه این محصول</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <ul class="nav nav-tabs">
              <li class="active"><a href="#tab-description" data-toggle="tab">توضیحات</a></li>
              <li><a href="#tab-specification" data-toggle="tab">مشخصات</a></li>
            </ul>
            <div class="tab-content">
              <div itemprop="description" id="tab-description" class="tab-pane active">
                <div>
                    <p>{{ product.description }}</p>
                </div>
              </div>
            </div>
            <h3 class="subtitle">محصولات مرتبط</h3>
            <div class="owl-carousel related_pro">
              {% for product in related_product %}
                   <div class="product-thumb">
                        <div class="image"><a href="product.html"><img src="{{ product.image.url}}" alt="{{ product.title}}" title="{{ product.title}}" class="img-responsive" /></a></div>
                        <div class="caption">
                          <h4><a href="{{ product.get_product_detail_url }}">{{product.title}}</a></h4>
                          <p class="price">
                              <span class="price-new">{{ product.price }} تومان</span>
                          </p>
                          <div class="rating"> <span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span> <span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span> <span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span> <span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span> <span class="fa fa-stack"><i class="fa fa-star-o fa-stack-2x"></i></span> </div>
                        </div>
                        <div class="button-group">
                            <a href="{{ product.get_product_detail_url }}">
                                  <button class="btn-primary" type="button" onClick=""><span>مشاهده مصحول</span></button>
                            </a>
                          <div class="add-to-links">
                            <button type="button" data-toggle="tooltip" title="افزودن به علاقه مندی" onClick=""><i class="fa fa-heart"></i></button>
                            <button type="button" data-toggle="tooltip" title="افزودن به مقایسه" onClick=""><i class="fa fa-exchange"></i></button>
                          </div>
                        </div>
                      </div>
                {% endfor %}
            </div>
          </div>
        </div>
        <!--Middle Part End -->
        <!--Right Part Start -->
        <aside id="column-right" class="col-sm-3 hidden-xs">
          <h3 class="subtitle">پرفروش ها</h3>
          <div class="side-item">
            <div class="product-thumb clearfix">
              <div class="image"><a href="product.html"><img src="{% static 'image/product/apple_cinema_30-50x50.jpg' %}" alt="تی شرت کتان مردانه" title="تی شرت کتان مردانه" class="img-responsive"></a></div>
              <div class="caption">
                <h4><a href="product.html">تی شرت کتان مردانه</a></h4>
                <p class="price"><span class="price-new">110000 تومان</span> <span class="price-old">122000 تومان</span> <span class="saving">-10%</span></p>
              </div>
            </div>
            <div class="product-thumb clearfix">
              <div class="image"><a href="product.html"><img src="{% static 'image/product/iphone_1-50x50.jpg' %}" alt="آیفون 7" title="آیفون 7" class="img-responsive"></a></div>
              <div class="caption">
                <h4><a href="product.html">آیفون 7</a></h4>
                <p class="price"> 2200000 تومان </p>
                <div class="rating"> <span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span> <span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span> <span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span> <span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span> <span class="fa fa-stack"><i class="fa fa-star-o fa-stack-2x"></i></span></div>
              </div>
            </div>
            <div class="product-thumb clearfix">
              <div class="image"><a href="product.html"><img src="{% static 'image/product/macbook_1-50x50.jpg' %}" alt="آیدیا پد یوگا" title="آیدیا پد یوگا" class="img-responsive"></a></div>
              <div class="caption">
                <h4><a href="product.html">آیدیا پد یوگا</a></h4>
                <p class="price"> 900000 تومان </p>
                <div class="rating"> <span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span> <span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span> <span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span> <span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span> <span class="fa fa-stack"><i class="fa fa-star-o fa-stack-2x"></i></span> </div>
              </div>
            </div>
            <div class="product-thumb clearfix">
              <div class="image"><a href="product.html"><img src="{% static 'image/product/sony_vaio_1-50x50.jpg' %}" alt="کفش راحتی مردانه" title="کفش راحتی مردانه" class="img-responsive"></a></div>
              <div class="caption">
                <h4><a href="product.html">کفش راحتی مردانه</a></h4>
                <p class="price"> <span class="price-new">32000 تومان</span> <span class="price-old">12 میلیون تومان</span> <span class="saving">-25%</span> </p>
                <div class="rating"> <span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span> <span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span> <span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span> <span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span> <span class="fa fa-stack"><i class="fa fa-star-o fa-stack-2x"></i></span> </div>
              </div>
            </div>
            <div class="product-thumb clearfix">
              <div class="image"><a href="product.html"><img src="{% static 'image/product/FinePix-Long-Zoom-Camera-50x50.jpg' %}" alt="دوربین فاین پیکس" title="دوربین فاین پیکس" class="img-responsive"></a></div>
              <div class="caption">
                <h4><a href="product.html">دوربین فاین پیکس</a></h4>
                <p class="price">122000 تومان</p>
              </div>
            </div>
          </div>

        {% render_partial 'products_categories_partial' %}

        </aside>

        <!--Right Part End -->
      </div>
    </div>
{% endblock %}

products/templates/product_item.html
<div class="product-layout product-grid col-lg-5ths col-md-5ths col-sm-4 col-xs-12">
    <div class="product-thumb">
        <div class="image"><a href="{{product.get_product_detail_url}}"><img src="{{product.image.url}}"
                    alt="{{product.title}}" title=" {{product.title}}" class="img-responsive"></a></div>
        <div>
            <div class="caption">
                <h4><a href="{{product.get_product_detail_url}}">{{product.title}}</a></h4>
                <p class="description">{{product.description}}</p>
                <p class="price"><span class="price-new">{{product.price}}تومان </span></p>
            </div>
            <div class="button-group">
                <a href="{{product.get_product_detail_url}}">
                    <button class="btn-primary" type="button"><span>مشاهده محصول</span></button>
                </a>
                <div class="add-to-links">
                    <button type="button" data-toggle="tooltip" title="" onclick=""
                        data-original-title="افزودن به علاقه مندی ها"><i class="fa fa-heart"></i> <span>افزودن به علاقه
                            مندی ها</span></button>
                    <button type="button" data-toggle="tooltip" title="" onclick=""
                        data-original-title="مقایسه این محصول"><i class="fa fa-exchange"></i> <span>مقایسه این
                            محصول</span></button>
                </div>
            </div>
        </div>
    </div>
</div>

products/templates/products_list.html
{% extends "base/base.html" %}
{% load render_partial %}
{% block content %}
<div class="container">
      <!-- Breadcrumb Start-->
      <!-- Breadcrumb End-->
      <div class="row">
        <!--Left Part Start -->
        <!--Left Part End -->
        <!--Middle Part Start-->
        <div id="content" class="col-sm-9">
          <h1 class="title">محصولات جدید</h1>
          <br>
          <div class="row products-category">
            {% for product in page_obj %}
              {% include "product_item.html" with product=product %}
            {% endfor %}

          </div>
          <div class="row">
            <div class="col-sm-6 text-left">
              <ul class="pagination">
                {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">قبلی</a></li>
                {% endif %}
                {% for page in paginator.page_range  %}
                    {% if page == page_obj.number %}
                        <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
                    {% else %}
                        <li><a href="?page={{ page }}">{{ page }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">بعدی</a></li>
                {% endif %}
              </ul>
            </div>
            <div class="col-sm-6 text-right">نمایش 1 تا 12 از 15 (مجموع 2 صفحه)</div>
          </div>
        </div>
        <!--Middle Part End -->
       
        <aside id="column-right" class="col-sm-3 hidden-xs">
            {% render_partial 'products_categories_partial' %}
        </aside>
      </div>
    </div>
{% endblock content %}